# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - arm1_controller
    - arm2_controller
    - agvBase_controller

  arm1_controller:
    type: FollowJointTrajectory
    joints:
      - arm1_joint1
      - arm1_joint2
      - arm1_joint3
      - arm1_joint4
      - arm1_joint5
      - arm1_joint6
    action_ns: follow_joint_trajectory
    default: true
  arm2_controller:
    type: FollowJointTrajectory
    joints:
      - arm2_joint1
      - arm2_joint2
      - arm2_joint3
      - arm2_joint4
      - arm2_joint5
      - arm2_joint6
    action_ns: follow_joint_trajectory
    default: true
  agvBase_controller:
    type: FollowJointTrajectory
    joints:
      - lifiting_joint
      - revolute_joint
    action_ns: follow_joint_trajectory
    default: true
